# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cookbook',
                'doc_host': 'https://Accessible-Data-and-Code.github.io',
                'git_url': 'https://github.com/Accessible-Data-and-Code/cookbook',
                'lib_path': 'cookbook'},
  'syms': {'cookbook.core': {'cookbook.core.foo': ('core.html#foo', 'cookbook/core.py')}}}
